# Generated by Django 2.2.5 on 2019-09-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oddam_w_dobre_rece_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_comment',
            field=models.TextField(null=True),
        ),
    ]
