# Generated by Django 2.2.5 on 2019-09-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oddam_w_dobre_rece_app', '0002_auto_20190917_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('password2', models.CharField(max_length=255)),
                ('username', models.EmailField(max_length=254)),
            ],
        ),
    ]
