# Generated by Django 2.2.5 on 2019-09-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oddam_w_dobre_rece_app', '0003_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Person',
        ),
    ]
